cc_library(
    name = "util-lib",
    srcs = ["utils.cc"],
    hdrs = ["utils.h"],
    visibility = ["//:__pkg__"],
    deps = [
        "//core/base:datetime-lib",
        "//core/base:bad_input-lib",
        "//core/base:order-lib",
        "//core/filehelper:file_helper-lib",
    ],
)
